<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>br.ufrn.dpb</groupId>
        <artifactId>distributed-payment-broker</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>dpb-ledger</artifactId>
    <packaging>jar</packaging>
    <name>DPB Ledger</name>

    <dependencies>
        <dependency>
            <groupId>br.ufrn.dpb</groupId>
            <artifactId>dpb-middleware</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <mainClass>br.ufrn.dpb.ledger.Main</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
