<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>br.ufrn.dpb</groupId>
  <artifactId>distributed-payment-broker</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <modules>
    <module>dpb-protocol</module>
    <module>dpb-server</module>
    <module>dpb-client</module>
  </modules>
</project>
